apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-ingress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-ingress
  template:
    metadata:
      labels:
        app: cluster-ingress
    spec:
      containers:
        - name: cluster-ingress
          image: localhost:32000/cluster-ingress:1.0.8
          ports:
            - containerPort: 443
          volumeMounts:
            - mountPath: /var/www/cert
              name: ingress-cert-volume
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 300
      volumes:
        - name: ingress-cert-volume
          hostPath:
            path: /opt/kubernetes/data/ingress/cert
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-ingress-service
spec:
  type: NodePort
  selector:
    app: cluster-ingress
  ports:
    - name: https
      port: 443
      targetPort: 443
      nodePort: 31100
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31101
      protocol: TCP